### ISSUE TITLE
Enable Dart's strong mode lints

### ISSUE THREAD

**Issue by ueman** [cfug/dio#1372]
### Issue Description and Steps

This library should enable the following lint:
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-raw-types: true
```

Otherwise, it is sometime very hard to understand which types are expected to be returned or given.
