### ISSUE TITLE
`TypeError: Cannot read properties` with `BrowserHttpClientAdapter()` when debugging on Web

### ISSUE THREAD

**Issue by JemmyWang94** [cfug/dio#2282]
### Package

dio

### Version

5.6.0

### Operating-System

Web

### Adapter

Default Dio

### Dart Version

3.5.0

### Steps to Reproduce

BrowserHttpClientAdapter adapter = BrowserHttpClientAdapter();
adapter.withCredentials = true;
dio.httpClientAdapter = adapter;

### Expected Result

no error and work well.

### Actual Result

TypeError: Cannot read properties of undefined (reading 'new')
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ #0   fortex7/packages/fortexmobile/common/network/web/web_platform.dart.lib.js 18:57  createClientAdapter

in flutter 3.22.3, it work well

**Comment by JemmyWang94** [comment]
flutter: 3.24.0

**Comment by AlexV525** [comment]
Could you share the resolved version of `dio` and `dio_web_adapter` in your `pubspec.lock`?

**Comment by Dan-Crane** [comment]
Hi bro, I also faced this error. It happens only in the debug build:

```
  dio:
    dependency: "direct main"
    description:
      name: dio
      sha256: "0dfb6b6a1979dac1c1245e17cef824d7b452ea29bd33d3467269f9bef3715fb0"
      url: "https://pub.dev"
    source: hosted
    version: "5.6.0"
  dio_web_adapter:
    dependency: transitive
    description:
      name: dio_web_adapter
      sha256: "33259a9276d6cea88774a0000cfae0d861003497755969c92faa223108620dc8"
      url: "https://pub.dev"
    source: hosted
    version: "2.0.0"
```
